# Generated by Django 4.1 on 2022-09-19 16:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='your_name',
            new_name='announced_by',
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='announcement',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
