# Generated by Django 4.1 on 2022-09-20 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logmpesa',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='logmpesa',
            name='cumulative_amount',
        ),
        migrations.RemoveField(
            model_name='logmpesa',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='logmpesa',
            name='customer_phone_number',
        ),
        migrations.RemoveField(
            model_name='logmpesa',
            name='daily_total',
        ),
        migrations.RemoveField(
            model_name='logmpesa',
            name='dat',
        ),
        migrations.RemoveField(
            model_name='logmpesa',
            name='first_logged',
        ),
        migrations.RemoveField(
            model_name='logmpesa',
            name='last_edited',
        ),
        migrations.RemoveField(
            model_name='logmpesa',
            name='logged_by',
        ),
        migrations.RemoveField(
            model_name='logmpesa',
            name='site_name',
        ),
        migrations.RemoveField(
            model_name='logmpesa',
            name='transaction_number',
        ),
        migrations.RemoveField(
            model_name='logmpesa',
            name='user',
        ),
    ]
