# Generated by Django 4.1 on 2022-09-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0002_remove_log_pump_log_fuelreceived_pump_log_pump'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='amount_earned_today',
        ),
        migrations.RemoveField(
            model_name='log',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='log',
            name='balance_yesterday',
        ),
        migrations.RemoveField(
            model_name='log',
            name='total_litres_sold',
        ),
        migrations.RemoveField(
            model_name='log',
            name='updated_balance',
        ),
        migrations.RemoveField(
            model_name='pump',
            name='initial_tank_litres',
        ),
        migrations.AddField(
            model_name='fuel',
            name='amount_earned_today',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fuel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='fuel',
            name='balance_yesterday',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='fuel',
            name='total_litres_sold_today',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='fuel',
            name='updated_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='pump',
            name='amount_earned_today',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pump',
            name='total_litres_sold_today',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
