# Generated by Django 4.1 on 2022-09-20 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0002_remove_logmpesa_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logmpesa',
            name='amount',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='logmpesa',
            name='amount_transferred_to_bank',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logmpesa',
            name='cumulative_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logmpesa',
            name='customer_name',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='logmpesa',
            name='customer_phone_number',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='logmpesa',
            name='daily_total',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logmpesa',
            name='first_logged',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='logmpesa',
            name='last_edited',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='logmpesa',
            name='logged_by',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='logmpesa',
            name='site_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='log_app.site'),
        ),
        migrations.AddField(
            model_name='logmpesa',
            name='transaction_number',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='logmpesa',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
