# Generated by Django 4.1 on 2022-10-09 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0002_logcreditcard_fuel_logmpesa_fuel_alter_myuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='formatted_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='logcreditcard',
            name='cumulative_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logcreditcard',
            name='daily_total',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logcreditcard',
            name='first_logged',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='logcreditcard',
            name='fuel_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='logcreditcard',
            name='last_edited',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='logcreditcard',
            name='site_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='log_app.site'),
        ),
        migrations.AddField(
            model_name='logcreditcard',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logmpesa',
            name='fuel_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
