# Generated by Django 4.1 on 2022-12-02 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0002_profile_is_staff_profile_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
