# Generated by Django 4.1 on 2022-09-12 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0002_alter_myuser_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='amount_earned_today',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
