# Generated by Django 4.1 on 2022-10-14 02:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0003_log_formatted_date_logcreditcard_cumulative_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logcreditcard',
            name='card_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1000000000000000), django.core.validators.MaxValueValidator(9999999999999999)]),
        ),
    ]
