# Generated by Django 4.1 on 2022-09-21 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0003_logmpesa_amount_logmpesa_amount_transferred_to_bank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logmpesa',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='logmpesa',
            name='amount_transferred_to_bank',
        ),
        migrations.RemoveField(
            model_name='logmpesa',
            name='cumulative_amount',
        ),
        migrations.RemoveField(
            model_name='logmpesa',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='logmpesa',
            name='customer_phone_number',
        ),
        migrations.RemoveField(
            model_name='logmpesa',
            name='daily_total',
        ),
        migrations.RemoveField(
            model_name='logmpesa',
            name='date',
        ),
        migrations.RemoveField(
            model_name='logmpesa',
            name='first_logged',
        ),
        migrations.RemoveField(
            model_name='logmpesa',
            name='last_edited',
        ),
        migrations.RemoveField(
            model_name='logmpesa',
            name='logged_by',
        ),
        migrations.RemoveField(
            model_name='logmpesa',
            name='site_name',
        ),
        migrations.RemoveField(
            model_name='logmpesa',
            name='user',
        ),
    ]
