# Generated by Django 4.1 on 2022-09-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0003_remove_log_amount_earned_today_remove_log_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='pump_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
