# Generated by Django 4.1 on 2022-09-12 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0003_log_amount_earned_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
