# Generated by Django 4.1 on 2022-12-03 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0004_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deleterequest',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='deleterequest',
            name='amount_td',
        ),
        migrations.RemoveField(
            model_name='deleterequest',
            name='bal',
        ),
        migrations.RemoveField(
            model_name='deleterequest',
            name='card_name',
        ),
        migrations.RemoveField(
            model_name='deleterequest',
            name='card_no',
        ),
        migrations.RemoveField(
            model_name='deleterequest',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='deleterequest',
            name='customer_no',
        ),
        migrations.RemoveField(
            model_name='deleterequest',
            name='eod_reading',
        ),
        migrations.RemoveField(
            model_name='deleterequest',
            name='eod_yesterday',
        ),
        migrations.RemoveField(
            model_name='deleterequest',
            name='litres_sold',
        ),
        migrations.RemoveField(
            model_name='deleterequest',
            name='to_bank',
        ),
        migrations.RemoveField(
            model_name='deleterequest',
            name='transaction_no',
        ),
    ]
