# Generated by Django 4.1 on 2022-10-14 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0004_alter_logcreditcard_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logcreditcard',
            name='card_number',
            field=models.IntegerField(),
        ),
    ]
