# Generated by Django 4.1 on 2022-09-21 04:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0004_remove_logmpesa_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logmpesa',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
