# Generated by Django 4.1 on 2022-09-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0004_log_pump_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pump',
            name='amount_earned_today',
        ),
        migrations.RemoveField(
            model_name='pump',
            name='total_litres_sold_today',
        ),
        migrations.AddField(
            model_name='log',
            name='amount_earned_today',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='total_litres_sold_today',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
