# Generated by Django 4.1 on 2022-12-05 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0005_remove_deleterequest_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='employee_id',
        ),
    ]
