# Generated by Django 4.1 on 2022-09-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0005_rename_site_name_petrolstation_petrol_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petrolstation',
            name='petrol_station',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
