# Generated by Django 4.1 on 2022-09-24 09:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0005_remove_pump_amount_earned_today_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuel',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
