# Generated by Django 4.1 on 2022-09-24 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0006_fuel_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='total_litres_sold_today',
            new_name='total_litres_sold',
        ),
    ]
