# Generated by Django 4.1 on 2022-09-21 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0006_logmpesa_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='logmpesa',
            name='logged_by',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
