# Generated by Django 4.1 on 2022-12-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0006_remove_myuser_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='tank_init',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
