# Generated by Django 4.1 on 2022-09-21 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0007_logmpesa_logged_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='logmpesa',
            name='customer_name',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='logmpesa',
            name='customer_phone_number',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
