# Generated by Django 4.1 on 2022-10-14 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0007_alter_logcreditcard_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='logcreditcard',
            name='formatted_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='logmpesa',
            name='formatted_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
