# Generated by Django 4.1 on 2022-09-13 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0007_rename_petrolstation_site'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='user',
            new_name='user_id',
        ),
    ]
