# Generated by Django 4.1 on 2022-09-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0007_rename_total_litres_sold_today_log_total_litres_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='total_litres_sold',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True),
        ),
    ]
