# Generated by Django 4.1 on 2022-10-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0008_logcreditcard_formatted_date_logmpesa_formatted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='edited_by',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='logcreditcard',
            name='edited_by',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='logmpesa',
            name='edited_by',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
