# Generated by Django 4.1 on 2022-09-13 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0008_rename_user_log_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
