# Generated by Django 4.1 on 2022-09-27 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0009_pump_amount_earned_today_pump_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuelreceived',
            name='pump',
        ),
    ]
