# Generated by Django 4.1 on 2022-09-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0010_alter_logmpesa_amount_transferred_to_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='fuel_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
