# Generated by Django 4.1 on 2022-09-27 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0010_remove_fuelreceived_pump'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='your_email',
            field=models.EmailField(blank=True, max_length=250, null=True),
        ),
    ]
