# Generated by Django 4.1 on 2022-10-06 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0011_incident_your_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='price_per_litre',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
