# Generated by Django 4.1 on 2022-09-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0011_log_fuel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelreceived',
            name='fuel_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
