# Generated by Django 4.1 on 2022-09-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0012_fuelreceived_fuel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelreceived',
            name='total_fuel_received_today',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fuelreceived',
            name='litres_received',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
