# Generated by Django 4.1 on 2022-09-13 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0013_alter_fuel_price_per_litre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel',
            name='initial_litres_in_tank',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
