# Generated by Django 4.1 on 2022-09-22 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0013_fuelreceived_total_fuel_received_today_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logreport',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='logreport',
            name='admin_email',
            field=models.EmailField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='logreport',
            name='admin_name',
            field=models.CharField(default='', max_length=120),
        ),
    ]
