# Generated by Django 4.1 on 2022-10-08 03:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0013_logcreditcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(blank=True, null=True)),
                ('card_name', models.CharField(blank=True, max_length=120, null=True)),
                ('card_number', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('logged_by', models.CharField(blank=True, max_length=120, null=True)),
                ('admin_name', models.CharField(blank=True, max_length=120, null=True)),
                ('admin_email', models.EmailField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='logcreditcard',
            name='logged_by',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
