# Generated by Django 4.1 on 2022-10-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0014_creditcardreport_logcreditcard_logged_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='nature',
            field=models.CharField(choices=[('Equipment_Failure', 'Equipment_Failure'), ('Physical_Injury', 'Physical_Injury'), ('EMERGENCY', 'EMERGENCY')], max_length=100),
        ),
    ]
