# Generated by Django 4.1 on 2022-09-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0016_logmpesa_cumulative_amount_logmpesa_daily_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesareport',
            name='transaction_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
