# Generated by Django 4.1 on 2022-10-24 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0020_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(blank=True, max_length=120, null=True)),
                ('admin_email', models.EmailField(blank=True, max_length=120, null=True)),
                ('requested_by', models.CharField(blank=True, max_length=120, null=True)),
                ('log_id', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('transaction_number', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=120, null=True)),
                ('customer_phone_number', models.PositiveBigIntegerField(blank=True, null=True)),
                ('amount', models.PositiveBigIntegerField(blank=True, null=True)),
                ('amount_transferred_to_bank', models.BigIntegerField(blank=True, null=True)),
                ('logged_by', models.CharField(blank=True, max_length=120, null=True)),
                ('eod_reading_lts', models.IntegerField(blank=True, null=True)),
                ('eod_reading_yesterday', models.IntegerField(blank=True, null=True)),
                ('litres_sold_today', models.IntegerField(blank=True, null=True)),
                ('amount_earned_today', models.PositiveBigIntegerField(blank=True, null=True)),
                ('balance', models.PositiveIntegerField(blank=True, null=True)),
                ('card_name', models.CharField(blank=True, max_length=120, null=True)),
                ('card_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
