# Generated by Django 4.1 on 2022-10-24 02:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0021_deleterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='deleterequest',
            name='date_requested',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
