# Generated by Django 4.1 on 2022-10-24 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0022_deleterequest_date_requested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deleterequest',
            name='date',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
