# Generated by Django 4.1 on 2022-10-24 04:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0023_alter_deleterequest_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deleterequest',
            name='date_requested',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
        ),
    ]
