# Generated by Django 4.1 on 2022-10-24 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0024_alter_deleterequest_date_requested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deleterequest',
            name='eod_reading_lts',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='deleterequest',
            name='eod_reading_yesterday',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
    ]
