# Generated by Django 4.1 on 2022-10-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0025_alter_deleterequest_eod_reading_lts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deleterequest',
            name='litres_sold_today',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
