# Generated by Django 4.1 on 2022-10-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0027_alter_deleterequest_litres_sold_today'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logreport',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='logreport',
            name='eod_reading_lts',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='logreport',
            name='eod_reading_yesterday',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='logreport',
            name='litres_sold_today',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
