# Generated by Django 4.1 on 2022-10-25 10:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0032_alter_logreport_amount_earned_today_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcardreport',
            name='card_number',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000000000000000), django.core.validators.MaxValueValidator(9999999999999999)]),
        ),
    ]
