# Generated by Django 4.1 on 2022-10-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0033_alter_creditcardreport_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcardreport',
            name='cumulative_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditcardreport',
            name='daily_total',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
