# Generated by Django 4.1 on 2022-10-29 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0036_alter_myuser_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='fuel_name',
        ),
        migrations.RemoveField(
            model_name='log',
            name='price_per_litre',
        ),
        migrations.RemoveField(
            model_name='log',
            name='pump_name',
        ),
        migrations.RemoveField(
            model_name='logcreditcard',
            name='fuel_name',
        ),
        migrations.RemoveField(
            model_name='logmpesa',
            name='fuel_name',
        ),
        migrations.AlterField(
            model_name='fuel',
            name='initial_litres_in_tank',
            field=models.DecimalField(decimal_places=2, error_messages={'decimal_places': 'Initial litres should have two decimal places.', 'max_digits': 'Initial litres should not be more than 8 digits.'}, max_digits=8),
        ),
        migrations.AlterField(
            model_name='fuel',
            name='price_per_litre',
            field=models.DecimalField(decimal_places=2, error_messages={'decimal_places': 'Price should have two decimal places.', 'max_digits': 'Price should not be more than 5 digits.'}, max_digits=5),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='employee_id',
            field=models.PositiveIntegerField(choices=[(12345, 12345), (67891, 67891), (102030, 102030), (405060, 405060), (708090, 708090), (112233, 112233), (445566, 445566), (778899, 778899), (101010, 101010), (202020, 202020), (303030, 303030), (404040, 404040), (505050, 505050)], error_messages={'invalid_choice': "No user with this ID '%r' exists.", 'unique': 'A user with this ID already exists.'}, unique=True, verbose_name='employee id'),
        ),
        migrations.AlterField(
            model_name='pump',
            name='initial_litres_in_tank',
            field=models.DecimalField(decimal_places=2, default=0, error_messages={'decimal_places': 'Initial litres should have two decimal places.', 'max_digits': 'Initial litres should not be more than 8 digits.'}, max_digits=8),
        ),
    ]
