# Generated by Django 4.1 on 2022-10-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0037_remove_log_fuel_name_remove_log_price_per_litre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuel',
            name='amount_earned_today',
        ),
        migrations.RemoveField(
            model_name='fuel',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='fuel',
            name='balance_yesterday',
        ),
        migrations.RemoveField(
            model_name='fuel',
            name='date',
        ),
        migrations.RemoveField(
            model_name='fuel',
            name='total_litres_sold_today',
        ),
        migrations.RemoveField(
            model_name='fuel',
            name='updated_balance',
        ),
        migrations.RemoveField(
            model_name='fuelreceived',
            name='fuel_name',
        ),
        migrations.RemoveField(
            model_name='pump',
            name='amount_earned_today',
        ),
        migrations.RemoveField(
            model_name='pump',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='pump',
            name='balance_yesterday',
        ),
        migrations.RemoveField(
            model_name='pump',
            name='date',
        ),
        migrations.RemoveField(
            model_name='pump',
            name='total_litres_sold_today',
        ),
        migrations.RemoveField(
            model_name='pump',
            name='updated_balance',
        ),
        migrations.AddField(
            model_name='log',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='balance_yesterday',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='cumulative_amount_today',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='cumulative_balance_today',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='cumulative_litres_sold_today',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='updated_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
