# Generated by Django 4.1 on 2022-11-03 13:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0039_remove_log_cumulative_amount_today_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('cumulative_litres_sold_today', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True)),
                ('cumulative_amount_today', models.PositiveBigIntegerField(blank=True, null=True)),
                ('cumulative_balance_today', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('fuel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='log_app.fuel')),
            ],
        ),
        migrations.AlterField(
            model_name='log',
            name='eod_reading_yesterday',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.DeleteModel(
            name='FuelSummary',
        ),
        migrations.AddField(
            model_name='summary',
            name='log',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='log_app.log'),
        ),
        migrations.AddField(
            model_name='summary',
            name='pump',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='log_app.pump'),
        ),
    ]
