# Generated by Django 4.1 on 2022-11-03 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0040_summary_alter_log_eod_reading_yesterday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='fuel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='log_app.fuel'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='pump',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='log_app.pump'),
        ),
    ]
