# Generated by Django 4.1 on 2022-11-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0042_remove_pump_fuel_fuel_pump'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuel',
            name='pump',
        ),
        migrations.AddField(
            model_name='fuel',
            name='pump',
            field=models.ManyToManyField(to='log_app.pump'),
        ),
    ]
