# Generated by Django 4.1 on 2022-11-03 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0043_remove_fuel_pump_fuel_pump'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuel',
            name='pump',
        ),
        migrations.AddField(
            model_name='fuel',
            name='pump',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='log_app.pump'),
        ),
    ]
