# Generated by Django 4.1 on 2022-11-03 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0044_remove_fuel_pump_fuel_pump'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel',
            name='pump',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='log_app.pump'),
        ),
        migrations.AlterField(
            model_name='log',
            name='fuel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='log_app.fuel'),
        ),
        migrations.AlterField(
            model_name='log',
            name='pump',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='log_app.pump'),
        ),
    ]
