# Generated by Django 4.1 on 2022-11-03 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0046_alter_fuel_pump_alter_log_fuel_alter_log_pump'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuel',
            name='pump',
        ),
        migrations.RemoveField(
            model_name='pump',
            name='initial_litres_in_tank',
        ),
        migrations.AddField(
            model_name='pump',
            name='fuel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='log_app.fuel'),
        ),
    ]
