# Generated by Django 4.1 on 2022-11-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0047_remove_fuel_pump_remove_pump_initial_litres_in_tank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pump',
            name='pump_name',
            field=models.CharField(default='', max_length=60),
        ),
    ]
