# Generated by Django 4.1 on 2022-11-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0048_alter_pump_pump_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='fuel',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='pump',
        ),
        migrations.AddField(
            model_name='summary',
            name='fuel_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='summary',
            name='pump_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
