# Generated by Django 4.1 on 2022-11-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0049_remove_summary_fuel_remove_summary_pump_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='log',
        ),
        migrations.AddField(
            model_name='summary',
            name='log_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
