# Generated by Django 4.1 on 2022-11-03 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0050_remove_summary_log_summary_log_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='log_id',
        ),
        migrations.AddField(
            model_name='summary',
            name='log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='log_app.log'),
        ),
    ]
