# Generated by Django 4.1 on 2022-11-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0051_remove_summary_log_id_summary_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='eod_reading_yesterday',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
    ]
