# Generated by Django 4.1 on 2022-11-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0052_alter_log_eod_reading_yesterday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='cumulative_litres_sold_today',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
