# Generated by Django 4.1 on 2022-11-03 14:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0053_alter_summary_cumulative_litres_sold_today'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='amount_earned_today',
        ),
        migrations.RemoveField(
            model_name='log',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='log',
            name='total_litres_sold',
        ),
        migrations.RemoveField(
            model_name='log',
            name='updated_balance',
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('fuel_id', models.PositiveIntegerField(blank=True, null=True)),
                ('pump_id', models.PositiveIntegerField(blank=True, null=True)),
                ('total_litres_sold', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True)),
                ('amount_earned_today', models.PositiveBigIntegerField(blank=True, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('updated_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='log_app.log')),
            ],
        ),
    ]
