# Generated by Django 4.1 on 2022-11-11 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0054_remove_log_amount_earned_today_remove_log_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='log',
        ),
        migrations.AddField(
            model_name='log',
            name='amount_earned_today',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='cumulative_amount_today',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='cumulative_balance_today',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='cumulative_litres_sold_today',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='total_litres_sold',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='updated_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='balance_yesterday',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='log',
            name='eod_reading_lts',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='log',
            name='eod_reading_yesterday',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.DeleteModel(
            name='Details',
        ),
        migrations.DeleteModel(
            name='Summary',
        ),
    ]
