# Generated by Django 4.1 on 2022-11-24 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0057_alter_deleterequest_admin_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='amount_earned_today',
            field=models.PositiveBigIntegerField(blank=True, default=0.0, null=True),
        ),
    ]
