# Generated by Django 4.1 on 2022-11-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0058_alter_log_amount_earned_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='logmpesa',
            name='fuel_type',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='logmpesa',
            name='price_per_litre',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
