# Generated by Django 4.1 on 2022-11-27 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0060_logcreditcard_fuel_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='pump',
        ),
    ]
