# Generated by Django 4.1 on 2022-11-27 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0061_remove_log_pump'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='user_id',
            new_name='user',
        ),
    ]
