from django.conf.urls import include 
from django.urls import path,re_path as url 
from log_app import api_views 


urlpatterns = [
    url(r'^profile-details/<int:user_id>/$', api_views.ProfileDetails.as_view()),
    url(r'^our-fuels/$', api_views.RegisteredFuels.as_view()),
    url(r'^diesel-info/$', api_views.DieselInfo.as_view()),
    url(r'^gas-info/$', api_views.GasInfo.as_view()),
    url(r'^petrol-info/$', api_views.PetrolInfo.as_view()),    url(r'^diesel-info/$', api_views.DieselInfo.as_view()),
    url(r'^all-logs/$', api_views.AllLogs.as_view()),
    url(r'^logs-today/$', api_views.TodayLogs.as_view()),
    url(r'^user-logs/<int:user_id>/$', api_views.UserLogs.as_view()),
    url(r'^diesel-logs-today/$', api_views.TodayDieselLogs.as_view()),
    url(r'^diesel-logs-ii-today/$', api_views.TodayDieselLogsTwo.as_view()),
    url(r'^diesel-logs-iii-today/$', api_views.TodayDieselLogsThree.as_view()),
    url(r'^diesel-logs-iv-today/$', api_views.TodayDieselLogsFour.as_view()),
    url(r'^petrol-logs-today/$', api_views.TodayPetrolLogs.as_view()),
    url(r'^petrol-logs-ii-today/$', api_views.TodayPetrolLogsTwo.as_view()),
    url(r'^petrol-logs-iii-today/$', api_views.TodayPetrolLogsThree.as_view()),
    url(r'^petrol-logs-iv-today/$', api_views.TodayPetrolLogsFour.as_view()),
    url(r'^gas-logs-today/$', api_views.TodayGasLogs.as_view()),
    url(r'^gas-logs-ii-today/$', api_views.TodayGasLogsTwo.as_view()),
    url(r'^gas-logs-iii-today/$', api_views.TodayGasLogsThree.as_view()),
    url(r'^gas-logs-iv-today/$', api_views.TodayGasLogsFour.as_view()),
    url(r'^diesel-logs-yesterday/$', api_views.YesterdayDieselLogs.as_view()),
    url(r'^petrol-logs-yesterday/$', api_views.YesterdayPetrolLogs.as_view()),
    url(r'^gas-logs-yesterday/$', api_views.YesterdayGasLogs.as_view()),
    url(r'^all-mpesa-logs/$', api_views.AllMpesaLogs.as_view()),
    url(r'^mpesa-logs-today/$', api_views.TodayMpesaLogs.as_view()),
    url(r'^user-mpesa-logs/<int:user_id>/$', api_views.UserMpesaLogs.as_view()),
    url(r'^mpesa-cumulative/$', api_views.MpesaCumulative.as_view()),
    url(r'^mpesa-total-today/$', api_views.MpesaTodayTotal.as_view()),
    url(r'^diesel-logs-yesterday/$', api_views.YesterdayDieselLogs.as_view()),
    url(r'^total-diesel-received-today/$', api_views.TotalDieselReceivedToday.as_view()),
    url(r'^diesel-received-today/info/$', api_views.DieselReceivedTodayInfo.as_view()),
    url(r'^total-petrol-received-today/$', api_views.TotalPetrolReceivedToday.as_view()),
    url(r'^petrol-received-today/info/$', api_views.PetrolReceivedTodayInfo.as_view()),
    url(r'^total-gas-received-today/$', api_views.TotalGasReceivedToday.as_view()),
    url(r'^gas-received-today/info/$', api_views.GasReceivedTodayInfo.as_view()),
    url(r'^diesel-log-details/<int:log_id>/$', api_views.DieselLogDetails.as_view()),
    url(r'^petrol-log-details/<int:log_id>/$', api_views.PetrolLogDetails.as_view()),
    url(r'^gas-log-details/<int:log_id>/$', api_views.GasLogDetails.as_view()),
    url(r'^mpesa-log-details/<int:log_id>/$', api_views.MpesaLogDetails.as_view()),
    url(r'^past-logs/(\d{4}-\d{2}-\d{2})/$',api_views.PastLogs.as_view()),
]