from django.conf.urls import include 
from django.urls import path,re_path as url 
from log_app import views, api_views 


urlpatterns = [
    path('',views.home,name='home'),
    url(r'^profile-details/<int:user_id>/$', api_views.ProfileDetails.as_view(),name='profile_details'),
    url(r'^our-fuels/$', api_views.RegisteredFuels.as_view(),name='our_fuels'),
    url(r'^diesel-info/$', api_views.DieselInfo.as_view(),name='diesel_info'),
    url(r'^gas-info/$', api_views.GasInfo.as_view(),name='gas_info'),
    url(r'^petrol-info/$', api_views.PetrolInfo.as_view(),name='petrol_info'), 
    url(r'^all-logs/$', api_views.AllLogs.as_view(),name='all_logs'),
    url(r'^logs-today/$', api_views.TodayLogs.as_view(),name='logs_today'),
    url(r'^user-logs/<int:user_id>/$', api_views.UserLogs.as_view(),name='user_logs'),
    url(r'^diesel-logs-today/<int:diesel_id>/$', api_views.TodayDieselLogs.as_view(),name='diesel_logs_today'),
    url(r'^diesel-logs-ii-today/$', api_views.TodayDieselLogsTwo.as_view(),name='diesel_logs_ii_today'),
    url(r'^diesel-logs-iii-today/$', api_views.TodayDieselLogsThree.as_view(),name='diesel_logs_iii_today'),
    url(r'^diesel-logs-iv-today/$', api_views.TodayDieselLogsFour.as_view(),name='diesel_logs_iv_today'),
    url(r'^petrol-logs-today/$', api_views.TodayPetrolLogs.as_view(),name='petrol_logs_today'),
    url(r'^petrol-logs-ii-today/$', api_views.TodayPetrolLogsTwo.as_view(),name='petrol_logs_ii_today'),
    url(r'^petrol-logs-iii-today/$', api_views.TodayPetrolLogsThree.as_view(),name='petrol_logs_iii_today'),
    url(r'^petrol-logs-iv-today/$', api_views.TodayPetrolLogsFour.as_view(),name='petrol_logs_iv_today'),
    url(r'^gas-logs-today/$', api_views.TodayGasLogs.as_view(),name='gas_logs_today'),
    url(r'^gas-logs-ii-today/$', api_views.TodayGasLogsTwo.as_view(),name='gas_logs_ii_today'),
    url(r'^gas-logs-iii-today/$', api_views.TodayGasLogsThree.as_view(),name='gas_logs_iii_today'),
    url(r'^gas-logs-iv-today/$', api_views.TodayGasLogsFour.as_view(),name='gas_logs_iv_today'),
    url(r'^diesel-logs-yesterday/$', api_views.YesterdayDieselLogs.as_view(),name='diesel_logs_yesterday'),
    url(r'^petrol-logs-yesterday/$', api_views.YesterdayPetrolLogs.as_view(),name='petrol_logs_yesterday'),
    url(r'^gas-logs-yesterday/$', api_views.YesterdayGasLogs.as_view(),name='gas_logs_yesterday'),
    url(r'^all-mpesa-logs/$', api_views.AllMpesaLogs.as_view(),name='all_mpesa_logs'),
    url(r'^mpesa-logs-today/$', api_views.TodayMpesaLogs.as_view(),name='mpesa_logs_today'),
    url(r'^user-mpesa-logs/<int:user_id>/$', api_views.UserMpesaLogs.as_view(),name='user_mpesa_logs'),
    url(r'^mpesa-cumulative/$', api_views.MpesaCumulative.as_view(),name='mpesa_cumulative'),
    url(r'^mpesa-total-today/$', api_views.MpesaTodayTotal.as_view(),name='mpesa_total_today'),
    url(r'^diesel-logs-yesterday/$', api_views.YesterdayDieselLogs.as_view(),name='diesel_logs_yesterday'),
    url(r'^total-diesel-received-today/$', api_views.TotalDieselReceivedToday.as_view(),name='total_diesel_today'),
    url(r'^diesel-received-today/info/$', api_views.DieselReceivedTodayInfo.as_view(),name='diesel_received_today'),
    url(r'^total-petrol-received-today/$', api_views.TotalPetrolReceivedToday.as_view(),name='total_petrol_today'),
    url(r'^petrol-received-today/info/$', api_views.PetrolReceivedTodayInfo.as_view(),name='petrol_received_today'),
    url(r'^total-gas-received-today/$', api_views.TotalGasReceivedToday.as_view(),name='total_gas_today'),
    url(r'^gas-received-today/info/$', api_views.GasReceivedTodayInfo.as_view(),name='gas_received_today'),
    url(r'^diesel-log-details/<int:log_id>/$', api_views.DieselLogDetails.as_view(),name='diesel_log_details'),
    url(r'^petrol-log-details/<int:log_id>/$', api_views.PetrolLogDetails.as_view(),name='petrol_log_details'),
    url(r'^gas-log-details/<int:log_id>/$', api_views.GasLogDetails.as_view(),name='gas_log_details'),
    url(r'^mpesa-log-details/<int:log_id>/$', api_views.MpesaLogDetails.as_view(),name='mpesa_log_details'),
    url(r'^past-logs/(\d{4}-\d{2}-\d{2})/$',api_views.PastLogs.as_view(),name='past_logs'),
]